import Foundation
import InkstoneCore

/// A saved conversation.
struct StoredConversation: Codable, Identifiable, Hashable {
    let id: UUID
    var messages: [ChatMessage]
    var updated: Date

    init(id: UUID = UUID(), messages: [ChatMessage] = [], updated: Date = .now) {
        self.id = id
        self.messages = messages
        self.updated = updated
    }

    /// A name taken from the first thing asked.
    ///
    /// Not generated by a model, which is what several clients do: that spends
    /// a request and a wait on a label, and the first line of the question is
    /// almost always the better name anyway — it is what the person will
    /// remember typing.
    var title: String {
        guard let first = messages.first(where: { $0.role == .user })?.text,
              !first.isEmpty else {
            return String(localized: "New conversation")
        }
        let line = first.split(separator: "\n").first.map(String.init) ?? first
        return line.count > 60 ? String(line.prefix(60)) + "…" : line
    }

    var isEmpty: Bool { messages.isEmpty }
}

/// Every conversation, on disk.
///
/// In Application Support rather than in the vault. A vault is synced to GitHub
/// and read by other tools; chat transcripts are neither notes nor something
/// anyone wants in a commit, and putting them there would push them to a
/// repository the moment sync ran.
@MainActor
@Observable
final class ConversationStore {
    private(set) var conversations: [StoredConversation] = []
    /// Which one is open. Never nil once loaded — an empty list gets an empty
    /// conversation, so the panel always has somewhere to type.
    var activeID: UUID?

    /// Beyond this, the oldest are dropped on save.
    ///
    /// A cap rather than unbounded history: these are read back in full at
    /// launch, and a year of daily use would make that a visible pause for a
    /// list nobody scrolls to the bottom of.
    private let limit = 100

    private let url: URL

    init(directory: URL? = nil) {
        let base = directory ?? FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appending(path: "Inkstone")
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        url = base.appending(path: "conversations.json")
        load()
    }

    var active: StoredConversation? {
        guard let activeID else { return conversations.first }
        return conversations.first { $0.id == activeID } ?? conversations.first
    }

    // MARK: - Editing

    /// Replaces the active conversation's messages, creating one if needed.
    func update(messages: [ChatMessage]) {
        guard let id = activeID ?? conversations.first?.id else {
            var fresh = StoredConversation(messages: messages)
            fresh.updated = .now
            conversations.insert(fresh, at: 0)
            activeID = fresh.id
            save()
            return
        }
        guard let index = conversations.firstIndex(where: { $0.id == id }) else { return }
        conversations[index].messages = messages
        conversations[index].updated = .now
        // Most recent first, which is the order anyone looks in.
        conversations.sort { $0.updated > $1.updated }
        save()
    }

    /// Starts a new conversation, reusing an existing empty one.
    ///
    /// Without the reuse, pressing New twice leaves two blank entries in the
    /// list, and the button appears not to have worked the second time.
    @discardableResult
    func startNew() -> UUID {
        if let existing = conversations.first(where: \.isEmpty) {
            activeID = existing.id
            return existing.id
        }
        let fresh = StoredConversation()
        conversations.insert(fresh, at: 0)
        activeID = fresh.id
        save()
        return fresh.id
    }

    func delete(_ id: UUID) {
        conversations.removeAll { $0.id == id }
        if activeID == id { activeID = conversations.first?.id }
        if conversations.isEmpty { startNew() }
        save()
    }

    func deleteAll() {
        conversations = []
        activeID = nil
        startNew()
        save()
    }

    // MARK: - Persistence

    private func load() {
        guard let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([StoredConversation].self, from: data)
        else {
            startNew()
            return
        }
        conversations = decoded.sorted { $0.updated > $1.updated }
        activeID = conversations.first?.id
        if conversations.isEmpty { startNew() }
    }

    private func save() {
        var toSave = conversations
        // Empty conversations are working state, not history. Saving them means
        // the list fills with blanks from every launch that opened the panel.
        toSave.removeAll { $0.isEmpty }
        if toSave.count > limit { toSave = Array(toSave.prefix(limit)) }
        guard let data = try? JSONEncoder().encode(toSave) else { return }
        try? data.write(to: url, options: .atomic)
    }
}
